
export const binaryOptions = [
    { label: "Yes", value: "yes" },
    { label: "No", value: "no" },
]

export const genderOptions = [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
    { value: "other", label: "Other" },
];

export const religionOptions = [
    { value: "hindu", label: "Hindu" },
    { value: "muslim", label: "Muslim" },
    { value: "christian", label: "Christian" },
    { value: 'sikh', label: "Sikh" },
    { value: 'buddhist', label: "Buddhist" },
    { value: 'jain', label: "Jain" },
    { value: "other", label: "Other" },
];

export const nationalityOptions = [
    { label: "India", value: "india" },
    { label: "United States", value: "us" },
    { label: "United Kingdom", value: "uk" },
    { label: "Australia", value: "australia" },
    { label: "Canada", value: "canada" },
    { label: "Germany", value: "germany" },
    { label: "France", value: "france" },
    { label: "Italy", value: "italy" },
    { label: "Spain", value: "spain" },
    { label: "Japan", value: "japan" },
    { label: "China", value: "china" },
    { label: "Russia", value: "russia" },
    { label: "Brazil", value: "brazil" },
    { label: "Mexico", value: "mexico" },
    { label: "South Africa", value: "south_africa" },
    { label: "Nigeria", value: "nigeria" },
    { label: "Saudi Arabia", value: "saudi_arabia" },
    { label: "United Arab Emirates", value: "uae" },
    { label: "Egypt", value: "egypt" },
    { label: "Indonesia", value: "indonesia" },
    { label: "Malaysia", value: "malaysia" },
    { label: "Singapore", value: "singapore" },
    { label: "Bangladesh", value: "bangladesh" },
    { label: "Pakistan", value: "pakistan" },
    { label: "Argentina", value: "argentina" },
    { label: "Chile", value: "chile" },
    { label: "Colombia", value: "colombia" },
    { label: "Peru", value: "peru" },
    { label: "South Korea", value: "south_korea" },
    { label: "Thailand", value: "thailand" },
    { label: "Vietnam", value: "vietnam" },
    { label: "Philippines", value: "philippines" },
    { label: "New Zealand", value: "new_zealand" },
    { label: "Portugal", value: "portugal" },
    { label: "Netherlands", value: "netherlands" },
    { label: "Belgium", value: "belgium" },
    { label: "Sweden", value: "sweden" },
    { label: "Norway", value: "norway" },
    { label: "Denmark", value: "denmark" },
    { label: "Finland", value: "finland" },
    { label: "Switzerland", value: "switzerland" },
    { label: "Greece", value: "greece" },
    { label: "Poland", value: "poland" },
    { label: "Czech Republic", value: "czech_republic" },
    { label: "Hungary", value: "hungary" },
    { label: "Ukraine", value: "ukraine" },
    { label: "Romania", value: "romania" },
    { label: "Israel", value: "israel" },
    { label: "Turkey", value: "turkey" },
    { label: "Iran", value: "iran" },
    { label: "Iraq", value: "iraq" },
    { label: "Afghanistan", value: "afghanistan" },
    { label: "Kuwait", value: "kuwait" },
    { label: "Qatar", value: "qatar" },
    { label: "Oman", value: "oman" },
    { label: "Jordan", value: "jordan" },
    { label: "Lebanon", value: "lebanon" },
];

export const maritalOptions = [
    { label: "Single", value: "single" },
    { label: "Married", value: "married" },
    { label: "Divorced", value: "divorced" },
    { label: "Widowed", value: "widowed" },
]

export const bloodGroupOptions = [
    { label: "A+", value: "A+" },
    { label: "A-", value: "A-" },
    { label: "B+", value: "B+" },
    { label: "B-", value: "B-" },
    { label: "AB+", value: "AB+" },
    { label: "AB-", value: "AB-" },
    { label: "O+", value: "O+" },
    { label: "O-", value: "O-" },
];

export const childrenRelationshipOptions = [
    { label: "Sibling", value: "sibling" },
    { label: "Children", value: "children" }
]

export const postAppliedForOptions = [
    { label: "Accounts Executive", value: "accounts_executive" },
    {
        label: "Assistant General Manager",
        value: "assistant_general_manager",
    },
    { label: "Assistant Manager", value: "assistant_manager" },
    { label: "Auto Electrician", value: "auto_electrician" },
    { label: "Denter", value: "denter" },
    { label: "Deputy General Manager", value: "deputy_general_manager" },
    { label: "Deputy Manager", value: "deputy_manager" },
    { label: "Driver", value: "driver" },
    { label: "Electrician", value: "electrician" },
    { label: "Engineer", value: "engineer" },
    { label: "Executive", value: "executive" },
    { label: "Foreman", value: "foreman" },
    { label: "General Manager", value: "general_manager" },
    { label: "Head Hr & Admin", value: "head_hr_admin" },
    { label: "Helper", value: "helper" },
    { label: "House Keeping", value: "house_keeping" },
    {
        label: "Junior Accounts Executive",
        value: "junior_accounts_executive",
    },
    { label: "Junior Engineer", value: "junior_engineer" },
    { label: "Junior Executive", value: "junior_executive" },
    { label: "Junior Mechanic", value: "junior_mechanic" },
    { label: "Manager", value: "manager" },
    { label: "Mechanic", value: "mechanic" },
    { label: "Operator", value: "operator" },
    { label: "Piling Supervisor", value: "piling_supervisor" },
    { label: "Rigger", value: "rigger" },
    { label: "SAP Manager", value: "sap_manager" },
    { label: "Senior Engineer", value: "senior_engineer" },
    { label: "Senior General Manager", value: "senior_general_manager" },
    { label: "Site Engineer", value: "site_engineer" },
    { label: "Site Incharge", value: "site_incharge" },
    { label: "Senior Manager", value: "senior_manager" },
    { label: "Senior Sr Coordinator", value: "senior_sr_coordinator" },
    { label: "Senior DGM", value: "senior_dgm" },
    { label: "Senior Executive", value: "senior_executive" },
    { label: "Senior Foreman", value: "senior_foreman" },
    { label: "Senior Mechanic", value: "senior_mechanic" },
    { label: "Store Assistant", value: "store_assistant" },
    { label: "Supervisor", value: "supervisor" },
    { label: "System Admin", value: "system_admin" },
    { label: "Technician", value: "technician" },
    { label: "Welder", value: "welder" },
]

export const visaTypeOptions = [
    { label: "Business Visa", value: "business" },
    { label: "Dependent Visa", value: "dependent" },
    { label: "Diplomatic Visa", value: "diplomatic" },
    { label: "Investor Visa", value: "investor" },
    { label: "Resident Visa", value: "resident" },
    { label: "Student Visa", value: "student" },
    { label: "Tourist Visa", value: "tourist" },
    { label: "Transit Visa", value: "transit" },
    { label: "Work Visa", value: "work" },
]